[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.0"  # Ajuste para refletir a última versão correta
tag_format = "v$version"
version_files = ["pyproject.toml", "src/aivestbr/__init__.py"]
