repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Remove espaços em branco desnecessários
      - id: end-of-file-fixer  # Garante uma nova linha no final do arquivo
      - id: check-yaml  # Verifica se arquivos YAML estão corretos
      - id: check-json  # Verifica a sintaxe de arquivos JSON
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: "v3.3.4"
    hooks:
      - id: pylint
        args: ["--fail-under=9.0"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Use a versão mais recente
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
