repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Remove espaços em branco desnecessários
      - id: end-of-file-fixer  # Garante uma nova linha no final do arquivo
      - id: check-yaml  # Verifica se arquivos YAML estão corretos
      - id: check-json  # Verifica a sintaxe de arquivos JSON
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
