[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AIvestBR"  # Substitua pelo nome do seu projeto
version = "0.1.2"
description = "Projeto de Análise de Investimentos"
authors = [
    { name = "Leonardo Trindade", email = "leotavo@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "requests>=2.32.3",
    "numpy>=1.24.2",
    "pandas>=1.5.3",
    "matplotlib>=3.7.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.12.2",
    "python-dotenv>=1.0.0"
]

[tool.setuptools]
packages = ["src"]  # Certifique-se de que "src" é o diretório correto do seu projeto

[tool.bumpversion]
current_version = "0.1.2"
commit = true
tag = true

[tool.bumpversion.file]
"pyproject.toml" = { search = 'version = "{current_version}"', replace = 'version = "{new_version}"' }
