[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AIvestBR"
version = "0.4.0"
description = "Projeto de Análise de Investimentos"
authors = [
    { name = "Leonardo Trindade", email = "leotavo@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "requests>=2.32.3",
    "numpy>=1.24.2",
    "pandas>=1.5.3",
    "matplotlib>=3.7.1",
    "scikit-learn>=1.3.2",  # Corrigido para última versão estável
    "scipy>=1.11.4",  # Corrigido para última versão estável
    "seaborn>=0.12.2",
    "python-dotenv>=1.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]  # Melhor forma de encontrar pacotes automaticamente

[tool.bumpversion]
current_version = "0.4.0"
commit = true
tag = true

[tool.bumpversion.files]
"pyproject.toml" = { search = 'version = "{current_version}"', replace = 'version = "{new_version}"' }
"src/aivestbr/__init__.py" = { search = '__version__ = "{current_version}"', replace = '__version__ = "{new_version}"' }

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.0"  # Corrigido para refletir a última versão correta
tag_format = "v$version"
version_files = ["pyproject.toml", "src/aivestbr/__init__.py"]

